---
# More information about configuring your Travis build using this .travis.yml
# file can be found here: http://docs.travis-ci.com/user/build-configuration/

language: python
python: "2.7"

before_install:
  # Make sure we have the latest versions of all our packages.
  - sudo apt-get update -qq

install:
  # Install and configure Ansible (used to easily configure our environment).
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - ansible-galaxy install geerlingguy.apache geerlingguy.mysql geerlingguy.php geerlingguy.composer geerlingguy.drush

script:
  # Configure our environment using Ansible.
  - "ansible-playbook -i tests/inventory tests/setup.yml --connection=local --sudo"

  # TODO: Do some tests here...
  - "curl http://localhost/"
