---
# More information about configuring your Travis build using this .travis.yml
# file can be found here: http://docs.travis-ci.com/user/build-configuration/

language: python
python: "2.7"

before_install:
  # Make sure we have the latest versions of all our packages.
  - sudo apt-get update -qq

install:
  # Install and configure Ansible (used to easily configure our environment).
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - ansible-galaxy install -r requirements.txt --ignore-errors

before_script:
  # Configure our environment using Ansible.
  - "ansible-playbook -i tests/inventory tests/setup.yml --connection=local --sudo"

  # Debugging.
  - php --version
  - php --ini
  - php -m

  # Clone Drupal 8.
  # TODO: Might want to just use the geerlingguy.drupal role—that way it's a
  # simple matter of using that pre-installed copy of Drupal. Flexibility++
  - git clone --branch 8.0.x http://git.drupal.org/project/drupal.git drupal-8

script:
  # Run PHPUnit tests (See: https://www.drupal.org/node/2116263).
  - cd drupal-8/core
  - ./vendor/phpunit/phpunit/phpunit --coverage-text

  # TODO: More testing...
