---
# More information about configuring your Travis build using this .travis.yml
# file can be found here: http://docs.travis-ci.com/user/build-configuration/

language: python
python: "2.7"

before_install:
  # Make sure we have the latest versions of all our packages.
  - sudo apt-get update -qq

install:
  # Install and configure Ansible (used to easily configure our environment).
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - ansible-galaxy install -r requirements.txt --ignore-errors

before_script:
  # Configure our environment using Ansible.
  - "ansible-playbook -i tests/inventory tests/setup.yml --connection=local --sudo"

  # Debugging.
  - php --version
  - php --ini
  - php -m
  - apache2 -v

  # Test environment setup.
  - cd /var/www/drupal
  - drush --uri=http://drupaltest.dev/ dl -y honeypot
  - drush --uri=http://drupaltest.dev/ en -y honeypot simpletest path

script:
  - cd /var/www/drupal

  # Run simpletests on a core module.
  - php scripts/run-tests.sh --url http://drupaltest.dev/ Path

  # Run simpletests on a contrib module.
  - php scripts/run-tests.sh --url http://drupaltest.dev/ Honeypot

  # Make sure home page loads.
  - curl --head http://drupaltest.dev/

  # TODO: More testing...
